<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rb</string>
		<string>rxml</string>
		<string>builder</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)^
	    (\s*+
	        (module|class|def
	        |unless|if
	        |case
	        |begin
	        |for|while|until
	        |(  "(\\.|[^"])*+"          # eat a double quoted string
	         | '(\\.|[^'])*+'        # eat a single quoted string
	         |   [^#"']                # eat all but comments and strings
	         )*
	         (                 \s   (do|begin|case)
	         | [-+=&amp;|*/~%^&lt;&gt;~] \s*+ (if|unless)
	         )
	        )\b
	        (?! [^;]*+ ; .*? \bend\b )
	    |(  "(\\.|[^"])*+"              # eat a double quoted string
	     | '(\\.|[^'])*+'            # eat a single quoted string
	     |   [^#"']                    # eat all but comments and strings
	     )*
	     ( \{ (?!  [^}]*+ \} )
	     | \[ (?! [^\]]*+ \] )
	     )
	    ).*$
	|   [#] .*? \(fold\) \s*+ $         # Sune’s special marker
	</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(   (^|;) \s*+ end   \s*+ ([#].*)? $
		|   ^     \s*+ [}\]] \s*+ ([#].*)? $
		|   [#] .*? \(end\) \s*+ $    # Sune’s special marker
		)</string>
	<key>name</key>
	<string>RAD</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(^\s*)(?=class\s+.+ArduinoSketch)</string>
			<key>comment</key>
			<string>Uses lookahead to match classes that (may) inherit from ArduinoSketch; includes 'source.ruby' to avoid infinite recursion</string>
			<key>end</key>
			<string>^\1(?=end)\b</string>
			<key>name</key>
			<string>meta.rad.sketch</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(add_to_setup|array|assembler|define|delay|digitalWrite|formatted_print|input_pin|input_pins|output_pin|output_pin|post_process_ruby_to_c_methods|vars|serial_begin)\b</string>
			<key>name</key>
			<string>support.function.arduinosketch.rad</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.ruby</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ruby.rad</string>
	<key>uuid</key>
	<string>89E2FC93-3B32-4800-8FF4-14AB18C0B5A1</string>
</dict>
</plist>
